- hosts: localhost
  tasks:
    - name: Install yay
      become: true
      community.general.pacman:
        name: yay
      tags:
        - zsh
        - core
    - include_tasks: tasks/setup-zsh.yml
    - include_tasks: tasks/install-main.yml
