- hosts: localhost
  pre_tasks:
    - name: Install yay
      become: true
      community.general.pacman:
        name: yay
  vars:
    source_key: "{{ playbook_dir }}/.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  tasks:
    - include_tasks: tasks/ssh-keys.yml
    - include_tasks: tasks/git.yml
    - include_tasks: tasks/dotfiles.yml
    # - include_tasks: tasks/packages.yml
    - include_tasks: tasks/cron.yml
    - include_tasks: tasks/projects.yml
