- name: Ensure zsh is installed
  package:
    name: zsh
    state: present

- name: Change default shell to zsh for the current user
  become: true
  user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh
