- name: Ensure Docker service is started and enabled
  become: true
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add current user to Docker group
  become: true
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes
