- name: Install stow
  become: true
  community.general.pacman:
    name: stow
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: "https://github.com/mogottsch/dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
- name: Stow dotfiles
  shell: cd $HOME/dotfiles && ./install
