- name: Install stow
  become: true
  community.general.pacman:
    name: stow
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: git@github.com:mogottsch/dotfiles.git
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
- name: Stow dotfiles
  shell: cd $HOME/dotfiles && ./install
- name: Create emtpy .secrets in home directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.secrets"
    state: touch
