- name: Install environment packages
  community.general.pacman:
    executable: yay
    extra_args: "--builddir {{ lookup('env', 'HOME') }}/.cache/yay --batchinstall"
    name:
      - arandr
      - bat
      - blueman
      - copyq
      - discord
      - flameshot
      - gparted
      - pandoc
      - redshift
      - spotify
      - tldr
      - udiskie
      - urxvt-resize-font-git
      - vlc
      - x11-ssh-askpass
      - zaread-git
      - zathura
  tags:
    - environment
