- name: Install main packages
  community.general.pacman:
    executable: yay
    extra_args: --builddir /home/moritz/.cache/yay --batchinstall
    name:
      - google-chrome
      - oh-my-zsh
      - ranger
      - rofi
      - tmux
      - gvim # gvim enables +clipboard
  tags:
    - main
