- name: Install university packages
  community.general.pacman:
    executable: yay
    extra_args: --builddir /home/moritz/.cache/yay --batchinstall
    name:
      - insync
      - zoom
      - zotero
  tags:
    - uni
