- name: Install main packages
  community.general.pacman:
    executable: yay
    extra_args: --builddir /home/moritz/.cache/yay --batchinstall
    name:
      - google-chrome
      - oh-my-zsh
      - ranger
      - rofi
      - tmux
  tags:
    - main
- include_tasks: tasks/install-vim.yml
