- name: Install development packages
  community.general.pacman:
    executable: yay
    extra_args: --builddir /home/moritz/.cache/yay --batchinstall
    name:
      # - cuda
      - docker
      - docker-compose
      - firefox
      - gitkraken
      - nginx
      - ngrok
      - visual-studio-code-bin
  tags:
    - dev
