- name: Ensure vim-plug is installed
  ansible.builtin.command:
    cmd: >
      curl -fLo "{{ lookup('env', 'XDG_DATA_HOME') | default('~/.local/share', true) }}/nvim/site/autoload/plug.vim" --create-dirs
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    creates: "{{ lookup('env', 'XDG_DATA_HOME') | default('~/.local/share', true) }}/nvim/site/autoload/plug.vim"
- name: Ensure Vim plugins are installed
  shell: |
    nvim -c 'PlugInstall' -c 'qa!'
  args:
    executable: /bin/bash
