- name: Install ssh key private
  become_user: root
  copy:
    src: "{{ source_secrets}}"
    dest: "{{ dest_secrets}}"
    mode: 0600
- name: Install ssh key public
  copy:
    src: "{{ source_secrets }}"
    dest: "{{ dest_secrets }}"
    mode: 0644
