- name: Install ZSH
  become: true
  community.general.pacman:
    name: zsh
  tags:
    - zsh

- name: Change user shell to zsh
  become: yes
  user:
    name: "moritz"
    shell: /usr/bin/zsh
  tags:
    - zsh

- name: Install zsh plugins
  community.general.pacman:
    executable: yay
    extra_args: --builddir /home/moritz/.cache/yay --batchinstall
    name:
      - conda-zsh-completion
      - zsh-autosuggestions
      - zsh-completions
      - zsh-history-substring-search
      - zsh-syntax-highlighting
      - zsh-theme-powerlevel10k-git
      - zsh-vi-mode
  tags:
    - zsh
