- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "gottschling.moritz@gmail.com"
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Moritz Gottschling"
