- name: Install university packages
  community.general.pacman:
    executable: yay
    extra_args: "--builddir {{ lookup('env', 'HOME') }}/.cache/yay --batchinstall"
    name:
      - insync
      - zoom
      - zotero
  tags:
    - uni
