- name: Install vim
  community.general.pacman:
    executable: yay
    extra_args: "--builddir {{ lookup('env', 'HOME') }}/.cache/yay --batchinstall"
    name:
      - gvim # gvim enables +clipboard
  tags:
    - main
- name: Install vundle
  become_user: "{{ lookup('env', 'USER') }}"
  ansible.builtin.git:
    dest: ~/.vim/bundle/Vundle.vim
    repo: https://github.com/VundleVim/Vundle.vim.git
- name: Install vundle plugins
  become_user: "{{ lookup('env', 'USER') }}"
  ansible.builtin.shell:
    cmd: vim +PluginInstall +qall
